/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.bunnytasker;

public final class R {
  public static final class color {
    public static final int bunny_dark=0x7f010000;
    public static final int white=0x7f010001;
  }
  public static final class drawable {
    public static final int bunny_lavender=0x7f020000;
    public static final int crown_gold=0x7f020001;
    public static final int ic_launcher=0x7f020002;
    public static final int ic_launcher_foreground=0x7f020003;
  }
  public static final class id {
    public static final int app_icon=0x7f030000;
    public static final int balance_amount=0x7f030001;
    public static final int balance_card=0x7f030002;
    public static final int balance_detail=0x7f030003;
    public static final int balance_header=0x7f030004;
    public static final int btn_attach=0x7f030005;
    public static final int btn_deadline_task_clear=0x7f030006;
    public static final int btn_free_unlock=0x7f030007;
    public static final int btn_pair_reset=0x7f030008;
    public static final int btn_pay=0x7f030009;
    public static final int btn_prepay=0x7f03000a;
    public static final int btn_selflock_120=0x7f03000b;
    public static final int btn_selflock_15=0x7f03000c;
    public static final int btn_selflock_30=0x7f03000d;
    public static final int btn_selflock_60=0x7f03000e;
    public static final int btn_send=0x7f03000f;
    public static final int btn_setup_imap=0x7f030010;
    public static final int btn_show_qr=0x7f030011;
    public static final int btn_sub_bronze=0x7f030012;
    public static final int btn_sub_gold=0x7f030013;
    public static final int btn_sub_silver=0x7f030014;
    public static final int btn_unsub=0x7f030015;
    public static final int connection_crown=0x7f030016;
    public static final int deadline_task_countdown=0x7f030017;
    public static final int deadline_task_header=0x7f030018;
    public static final int deadline_task_hint=0x7f030019;
    public static final int deadline_task_section=0x7f03001a;
    public static final int deadline_task_status=0x7f03001b;
    public static final int deadline_task_text=0x7f03001c;
    public static final int imap_status=0x7f03001d;
    public static final int message_input=0x7f03001e;
    public static final int messages_container=0x7f03001f;
    public static final int messages_header=0x7f030020;
    public static final int no_sub_prompt=0x7f030021;
    public static final int paired_fingerprint=0x7f030022;
    public static final int pairing_code_hint=0x7f030023;
    public static final int pairing_code_text=0x7f030024;
    public static final int pairing_fingerprint=0x7f030025;
    public static final int pairing_hint=0x7f030026;
    public static final int pay_hint=0x7f030027;
    public static final int payment_history=0x7f030028;
    public static final int pinned_message=0x7f030029;
    public static final int pinned_section=0x7f03002a;
    public static final int qr_code=0x7f03002b;
    public static final int section_main_content=0x7f03002c;
    public static final int section_messages=0x7f03002d;
    public static final int section_paired=0x7f03002e;
    public static final int section_pairing=0x7f03002f;
    public static final int section_selflock=0x7f030030;
    public static final int section_stats=0x7f030031;
    public static final int stat_escapes=0x7f030032;
    public static final int stat_geofence=0x7f030033;
    public static final int stat_interest=0x7f030034;
    public static final int stat_paid=0x7f030035;
    public static final int stat_paywall=0x7f030036;
    public static final int stat_streak=0x7f030037;
    public static final int stat_today=0x7f030038;
    public static final int stat_total=0x7f030039;
    public static final int stat_week=0x7f03003a;
    public static final int status_bar=0x7f03003b;
    public static final int status_text=0x7f03003c;
    public static final int sub_perks=0x7f03003d;
    public static final int sub_status=0x7f03003e;
    public static final int tier_badge=0x7f03003f;
  }
  public static final class layout {
    public static final int activity_main=0x7f040000;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f050000;
    public static final int ic_launcher_foreground=0x7f050001;
  }
  public static final class string {
    public static final int app_name=0x7f060000;
  }
  public static final class style {
    public static final int BunnyTheme=0x7f070000;
  }
  public static final class xml {
    public static final int device_admin=0x7f080000;
    public static final int network_security_config=0x7f080001;
  }
}