/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.focusctl;

public final class R {
  public static final class color {
    public static final int bg=0x7f010000;
    public static final int ic_launcher_background=0x7f010001;
  }
  public static final class drawable {
    public static final int danger_block=0x7f020001;
    public static final int ic_launcher_foreground=0x7f020002;
    public static final int ic_launcher_monochrome=0x7f020003;
  }
  public static final class id {
    public static final int balance_display=0x7f030000;
    public static final int balance_set_input=0x7f030001;
    public static final int body_check_card=0x7f030002;
    public static final int body_check_status=0x7f030003;
    public static final int btn_add_1=0x7f030004;
    public static final int btn_add_10=0x7f030005;
    public static final int btn_add_25=0x7f030006;
    public static final int btn_add_5=0x7f030007;
    public static final int btn_add_50=0x7f030008;
    public static final int btn_body_check_baseline=0x7f030009;
    public static final int btn_body_check_now=0x7f03000a;
    public static final int btn_body_check_start=0x7f03000b;
    public static final int btn_clear_balance=0x7f03000c;
    public static final int btn_confine_home=0x7f03000d;
    public static final int btn_deadline_task=0x7f03000e;
    public static final int btn_entrap_adv=0x7f03000f;
    public static final int btn_force_sub=0x7f030010;
    public static final int btn_gamble=0x7f030011;
    public static final int btn_kebab=0x7f030012;
    public static final int btn_lock=0x7f030013;
    public static final int btn_lock_120=0x7f030014;
    public static final int btn_lock_15=0x7f030015;
    public static final int btn_lock_30=0x7f030016;
    public static final int btn_lock_60=0x7f030017;
    public static final int btn_offer_accept=0x7f030018;
    public static final int btn_offer_decline=0x7f030019;
    public static final int btn_pin_message=0x7f03001a;
    public static final int btn_play_audio=0x7f03001b;
    public static final int btn_schedule_message=0x7f03001c;
    public static final int btn_send_message=0x7f03001d;
    public static final int btn_set_balance=0x7f03001e;
    public static final int btn_set_geofence=0x7f03001f;
    public static final int btn_speak=0x7f030020;
    public static final int btn_start_fine=0x7f030021;
    public static final int btn_stop_fine=0x7f030022;
    public static final int btn_task=0x7f030023;
    public static final int btn_toy_pulse=0x7f030024;
    public static final int btn_toy_punish=0x7f030025;
    public static final int btn_toy_reward=0x7f030026;
    public static final int btn_toy_stop=0x7f030027;
    public static final int btn_unlock=0x7f030028;
    public static final int btn_unlock_device=0x7f030029;
    public static final int btn_veneration=0x7f03002a;
    public static final int compliment_prompt=0x7f03002b;
    public static final int device_cards_container=0x7f03002c;
    public static final int fine_status=0x7f03002d;
    public static final int inbox_e2ee_warning=0x7f03002e;
    public static final int inbox_message_input=0x7f03002f;
    public static final int lion_message_scroll=0x7f030030;
    public static final int lion_message_thread=0x7f030031;
    public static final int lion_payment_history=0x7f030032;
    public static final int menu_app_pin=0x7f030033;
    public static final int menu_bunnies=0x7f030034;
    public static final int menu_group_bunny=0x7f030035;
    public static final int menu_group_danger=0x7f030036;
    public static final int menu_group_setup=0x7f030037;
    public static final int menu_payment_email=0x7f030038;
    public static final int menu_release_forever=0x7f030039;
    public static final int menu_setup=0x7f03003a;
    public static final int menu_vault_nodes=0x7f03003b;
    public static final int menu_web_remote=0x7f03003c;
    public static final int message_input=0x7f03003d;
    public static final int mode_spinner=0x7f03003e;
    public static final int offer_counter=0x7f03003f;
    public static final int offer_section=0x7f030040;
    public static final int offer_text=0x7f030041;
    public static final int page_inbox=0x7f030042;
    public static final int page_lock=0x7f030043;
    public static final int page_money=0x7f030044;
    public static final int page_rules=0x7f030045;
    public static final int paywall_amount=0x7f030046;
    public static final int phone_spinner=0x7f030047;
    public static final int schedule_label=0x7f030048;
    public static final int sec_mods_body=0x7f030049;
    public static final int sec_mods_chevron=0x7f03004a;
    public static final int sec_mods_head=0x7f03004b;
    public static final int sec_mods_summary=0x7f03004c;
    public static final int sec_pokes_body=0x7f03004d;
    public static final int sec_pokes_chevron=0x7f03004e;
    public static final int sec_pokes_head=0x7f03004f;
    public static final int sec_pokes_summary=0x7f030050;
    public static final int setup_debug_port=0x7f030051;
    public static final int setup_https_url=0x7f030052;
    public static final int setup_lan_ip=0x7f030053;
    public static final int setup_mesh_url=0x7f030054;
    public static final int setup_pair_code=0x7f030055;
    public static final int setup_pair_port=0x7f030056;
    public static final int setup_result=0x7f030057;
    public static final int setup_tailscale_ip=0x7f030058;
    public static final int setup_vault_mode=0x7f030059;
    public static final int status=0x7f03005a;
    public static final int status_bar=0x7f03005b;
    public static final int sub_status_text=0x7f03005c;
    public static final int tab_inbox=0x7f03005d;
    public static final int tab_lock=0x7f03005e;
    public static final int tab_money=0x7f03005f;
    public static final int tab_rules=0x7f030060;
    public static final int task_input=0x7f030061;
    public static final int task_randomize=0x7f030062;
    public static final int task_reps=0x7f030063;
    public static final int tier_badge=0x7f030064;
    public static final int timer_input=0x7f030065;
    public static final int toggle_dim=0x7f030066;
    public static final int toggle_mandatory=0x7f030067;
    public static final int toggle_mute=0x7f030068;
    public static final int toggle_penalty=0x7f030069;
    public static final int toggle_pin_notif=0x7f03006a;
    public static final int toggle_shame=0x7f03006b;
    public static final int toggle_vibrate=0x7f03006c;
    public static final int toy_section=0x7f03006d;
  }
  public static final class layout {
    public static final int activity_main=0x7f040000;
    public static final int dialog_setup=0x7f040001;
  }
  public static final class menu {
    public static final int overflow=0x7f050000;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f060000;
  }
  public static final class raw {
    public static final int veneration_tasks=0x7f070000;
  }
  public static final class string {
    public static final int app_name=0x7f080000;
  }
  public static final class style {
    public static final int AppTheme=0x7f090000;
  }
  public static final class xml {
    public static final int network_security_config=0x7f0a0000;
  }
}