/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.focusctl;

public final class R {
  public static final class color {
    public static final int bg=0x7f010000;
    public static final int ic_launcher_background=0x7f010001;
  }
  public static final class id {
    public static final int balance_display=0x7f020000;
    public static final int balance_set_input=0x7f020001;
    public static final int body_check_status=0x7f020002;
    public static final int btn_add_1=0x7f020003;
    public static final int btn_add_10=0x7f020004;
    public static final int btn_add_25=0x7f020005;
    public static final int btn_add_5=0x7f020006;
    public static final int btn_add_50=0x7f020007;
    public static final int btn_app_pin=0x7f020008;
    public static final int btn_body_check_baseline=0x7f020009;
    public static final int btn_body_check_now=0x7f02000a;
    public static final int btn_body_check_start=0x7f02000b;
    public static final int btn_bunnies=0x7f02000c;
    public static final int btn_clear_balance=0x7f02000d;
    public static final int btn_clear_paywall=0x7f02000e;
    public static final int btn_confine_home=0x7f02000f;
    public static final int btn_deadline_task=0x7f020010;
    public static final int btn_entrap_adv=0x7f020011;
    public static final int btn_force_sub=0x7f020012;
    public static final int btn_gamble=0x7f020013;
    public static final int btn_lock=0x7f020014;
    public static final int btn_lock_120=0x7f020015;
    public static final int btn_lock_15=0x7f020016;
    public static final int btn_lock_30=0x7f020017;
    public static final int btn_lock_60=0x7f020018;
    public static final int btn_offer_accept=0x7f020019;
    public static final int btn_offer_decline=0x7f02001a;
    public static final int btn_payment_email=0x7f02001b;
    public static final int btn_pin_message=0x7f02001c;
    public static final int btn_play_audio=0x7f02001d;
    public static final int btn_release_forever=0x7f02001e;
    public static final int btn_schedule_message=0x7f02001f;
    public static final int btn_send_message=0x7f020020;
    public static final int btn_set_balance=0x7f020021;
    public static final int btn_set_geofence=0x7f020022;
    public static final int btn_setup=0x7f020023;
    public static final int btn_speak=0x7f020024;
    public static final int btn_start_fine=0x7f020025;
    public static final int btn_stop_fine=0x7f020026;
    public static final int btn_task=0x7f020027;
    public static final int btn_toy_pulse=0x7f020028;
    public static final int btn_toy_punish=0x7f020029;
    public static final int btn_toy_reward=0x7f02002a;
    public static final int btn_toy_stop=0x7f02002b;
    public static final int btn_unlock=0x7f02002c;
    public static final int btn_unlock_device=0x7f02002d;
    public static final int btn_vault_nodes=0x7f02002e;
    public static final int btn_web_remote=0x7f02002f;
    public static final int compliment_prompt=0x7f020030;
    public static final int device_cards_container=0x7f020031;
    public static final int fine_status=0x7f020032;
    public static final int inbox_message_input=0x7f020033;
    public static final int lion_message_thread=0x7f020034;
    public static final int lion_payment_history=0x7f020035;
    public static final int message_input=0x7f020036;
    public static final int mode_spinner=0x7f020037;
    public static final int offer_counter=0x7f020038;
    public static final int offer_section=0x7f020039;
    public static final int offer_text=0x7f02003a;
    public static final int page_advanced=0x7f02003b;
    public static final int page_inbox=0x7f02003c;
    public static final int page_simple=0x7f02003d;
    public static final int paywall_amount=0x7f02003e;
    public static final int phone_spinner=0x7f02003f;
    public static final int schedule_label=0x7f020040;
    public static final int setup_debug_port=0x7f020041;
    public static final int setup_https_url=0x7f020042;
    public static final int setup_lan_ip=0x7f020043;
    public static final int setup_mesh_url=0x7f020044;
    public static final int setup_pair_code=0x7f020045;
    public static final int setup_pair_port=0x7f020046;
    public static final int setup_result=0x7f020047;
    public static final int setup_tailscale_ip=0x7f020048;
    public static final int setup_vault_mode=0x7f020049;
    public static final int status=0x7f02004a;
    public static final int status_bar=0x7f02004b;
    public static final int sub_status_text=0x7f02004c;
    public static final int tab_advanced=0x7f02004d;
    public static final int tab_inbox=0x7f02004e;
    public static final int tab_simple=0x7f02004f;
    public static final int task_input=0x7f020050;
    public static final int task_randomize=0x7f020051;
    public static final int task_reps=0x7f020052;
    public static final int tier_badge=0x7f020053;
    public static final int timer_input=0x7f020054;
    public static final int toggle_dim=0x7f020055;
    public static final int toggle_mandatory=0x7f020056;
    public static final int toggle_mute=0x7f020057;
    public static final int toggle_penalty=0x7f020058;
    public static final int toggle_pin_notif=0x7f020059;
    public static final int toggle_shame=0x7f02005a;
    public static final int toggle_vibrate=0x7f02005b;
    public static final int toy_section=0x7f02005c;
  }
  public static final class layout {
    public static final int activity_main=0x7f030000;
    public static final int dialog_setup=0x7f030001;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f040000;
    public static final int ic_launcher_foreground=0x7f040001;
  }
  public static final class string {
    public static final int app_name=0x7f050000;
  }
  public static final class style {
    public static final int AppTheme=0x7f060000;
  }
  public static final class xml {
    public static final int network_security_config=0x7f070000;
  }
}