#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 The FocusLock Contributors
#
# Retrofit the local Linux desktop collar — pulls the latest tray, daemon,
# mesh, and shared modules from the canonical Nextcloud source tree, copies
# them into /opt/focuslock + ~/.config/focuslock, and restarts the daemons.
# Use this after a code change (e.g. new badged tray icon) to roll the
# update onto a machine that's already enslaved.
#
# Usage:
#   ./retrofit-local.sh              # retrofit this machine
#   ./retrofit-local.sh --dry-run    # show what would change
#
# Prereq: this machine is already enslaved (~/.config/focuslock/config.json
# exists with mesh_url). For a fresh install use install-desktop-collar.sh
# or one of the install-mesh-*.sh wrappers.
#
# Internally a thin wrapper over re-enslave-desktops.sh --local-only that
# auto-synthesizes ~/.config/focuslock/re-enslave.config from config.json
# so a freshly-paired machine doesn't have to be hand-configured first.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$HOME/.config/focuslock/config.json"
RE_CONFIG="$HOME/.config/focuslock/re-enslave.config"

if [ ! -f "$CONFIG" ]; then
    echo "error: $CONFIG not found — this machine isn't enslaved yet." >&2
    echo "  Run installers/install-desktop-collar.sh or installers/install-mesh-*.sh first." >&2
    exit 2
fi

# Synthesize re-enslave.config if missing — re-enslave-desktops.sh's
# check_paywall needs FOCUSLOCK_MESH_URL set somewhere (env or this file).
if [ ! -f "$RE_CONFIG" ]; then
    mesh_url=$(python3 -c "import json,sys; print(json.load(open('$CONFIG')).get('mesh_url',''))" 2>/dev/null || echo "")
    if [ -z "$mesh_url" ]; then
        echo "error: $CONFIG has no mesh_url — can't determine retrofit target." >&2
        exit 2
    fi
    mkdir -p "$(dirname "$RE_CONFIG")"
    cat > "$RE_CONFIG" <<EOF
# Auto-generated by retrofit-local.sh from config.json
FOCUSLOCK_MESH_URL="$mesh_url"
PHONE_TARGETS=()
EOF
    chmod 600 "$RE_CONFIG"
    echo "Wrote $RE_CONFIG (FOCUSLOCK_MESH_URL=$mesh_url)"
fi

exec bash "$SCRIPT_DIR/re-enslave-desktops.sh" --local-only "$@"
