# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 The FocusLock Contributors
"""
FocusLock Evidence Email — sends typed evidence to Lion via SMTP.

Handles compliments, gratitude journal entries, love letters, photo task
verdicts, escape attempts, geofence breaches, and other evidence types.
Respects per-type notification preferences from mesh orders or ADB.
"""

import logging
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


def get_notif_pref(key, mesh_orders, adb=None):
    """Read notification preference.  Checks mesh orders first, ADB fallback.

    Args:
        key: Preference key (e.g. "email_evidence", "email_escape").
        mesh_orders: MeshOrders instance (or dict-like with .get()).
        adb: Optional ADBBridge instance for ADB fallback.

    Returns:
        True if the notification is enabled (default).
    """
    val = mesh_orders.get(f"notif_{key}")
    if val is not None:
        return str(val) != "0"
    if adb:
        try:
            result = adb.get(f"focus_lock_notif_{key}")
            return result != "0"
        except Exception:
            pass
    return True  # default: enabled


# Map evidence types to notification preference keys
_TYPE_TO_PREF = {
    "compliment": "email_evidence",
    "gratitude": "email_evidence",
    "love letter": "email_evidence",
    "photo task passed": "email_evidence",
    "photo task failed": "email_evidence",
    "bunny message": "email_evidence",
    "exercise": "email_evidence",
    "self-lock": "email_escape",
    "entrap": "email_escape",
    "escape attempt": "email_escape",
    "geofence breach": "email_breach",
}


def send_evidence(
    text, evidence_type="compliment", *, mesh_orders, adb=None, partner_email, smtp_host, mail_user, mail_pass
):
    """Send evidence email to Lion.  Respects notification preferences.

    Args:
        text: The evidence content (compliment text, verdict, etc.).
        evidence_type: Category string for subject line and pref lookup.
        mesh_orders: MeshOrders instance for notification pref check.
        adb: Optional ADBBridge for ADB-based pref fallback.
        partner_email: Recipient email address.
        smtp_host: SMTP server hostname.
        mail_user: SMTP login username.
        mail_pass: SMTP login password.

    Returns:
        True if the email was sent, False otherwise.
    """
    if not partner_email:
        print(f"[evidence] No partner email configured, skipping {evidence_type}")
        return False

    # Check notification preferences
    pref_key = _TYPE_TO_PREF.get(evidence_type, "email_evidence")
    if not get_notif_pref(pref_key, mesh_orders, adb):
        print(f"[evidence] Email disabled for {evidence_type} (pref: {pref_key}), skipping")
        return False

    if not all([smtp_host, mail_user, mail_pass]):
        print(f"[evidence] SMTP not configured, skipping {evidence_type}")
        return False

    try:
        msg = MIMEMultipart()
        msg["From"] = mail_user
        msg["To"] = partner_email
        msg["Subject"] = f"Lion's Share \u2014 {evidence_type.title()} Evidence"

        body = (
            f"Lion's Share \u2014 {evidence_type.title()} Receipt\n\n"
            f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            f"Type: {evidence_type}\n\n"
            f"Content:\n{text}\n\n"
            f"---\n"
            f"This message was automatically generated by Lion's Share.\n"
            f"The above {evidence_type} was typed in full on the locked device to earn an unlock.\n"
            f"It cannot be disavowed.\n"
        )
        msg.attach(MIMEText(body, "plain"))

        with smtplib.SMTP(smtp_host, 587) as server:
            server.starttls()
            server.login(mail_user, mail_pass)
            server.send_message(msg)

        print(f"[evidence] Evidence email sent to {partner_email}")
        return True

    except Exception as e:
        print(f"[evidence] SMTP error for {evidence_type}: {e}")
        return False
