/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.focuslock;

public final class R {
  public static final class font {
    public static final int lexend=0x7f010000;
  }
  public static final class id {
    public static final int btn_bunny_tasker=0x7f020000;
    public static final int btn_factory_reset=0x7f020001;
    public static final int btn_take_photo=0x7f020002;
    public static final int compliment_input=0x7f020003;
    public static final int exercise_done=0x7f020004;
    public static final int exercise_timer=0x7f020005;
    public static final int focus_message=0x7f020006;
    public static final int freeform_input=0x7f020007;
    public static final int gratitude_1=0x7f020008;
    public static final int gratitude_2=0x7f020009;
    public static final int gratitude_3=0x7f02000a;
    public static final int gratitude_submit=0x7f02000b;
    public static final int offer_submit=0x7f02000c;
    public static final int paywall_banking=0x7f02000d;
    public static final int paywall_display=0x7f02000e;
    public static final int paywall_label=0x7f02000f;
    public static final int photo_status=0x7f020010;
    public static final int shame_display=0x7f020011;
    public static final int task_input=0x7f020012;
    public static final int task_prompt=0x7f020013;
    public static final int task_target=0x7f020014;
    public static final int word_counter=0x7f020015;
  }
  public static final class layout {
    public static final int activity_focus=0x7f030000;
  }
  public static final class style {
    public static final int FocusTheme=0x7f040000;
  }
  public static final class xml {
    public static final int device_admin=0x7f050000;
    public static final int network_security_config=0x7f050001;
  }
}